apiVersion: apps/v1
kind: Deployment
metadata:
  name: uas-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uas-backend
  template:
    metadata:
      labels:
        app: uas-backend
    spec:
      containers:
      - name: uas-backend-container
        image: awanbirunsiran000/uas-projeckt-devops:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        command: ["python", "app.py"]
---
apiVersion: v1
kind: Service
metadata:
  name: uas-fe-service 
spec:
  selector:
    app: uas-fe
  ports:
  - port: 8080
    targetPort: 5000
  type: LoadBalancer
